# Generated by Django 3.1.6 on 2021-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210217_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
