# Generated by Django 3.1.6 on 2021-02-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210221_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('isolate', models.CharField(max_length=200)),
                ('interaction_partner', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='effector_description',
            field=models.TextField(max_length=2.0, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='effector_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='effector_signal_peptide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='effector_sequence',
            field=models.TextField(max_length=10.0),
        ),
    ]
