# Generated by Django 3.1.6 on 2021-02-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210222_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_signal_peptide',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False'), ('A', 'Any')], default='A', max_length=1),
        ),
    ]
