# Generated by Django 3.1.6 on 2021-02-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210222_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_signal_peptide',
            field=models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False'), ('', '')], default='', max_length=1),
        ),
    ]
