# Generated by Django 3.1.6 on 2021-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20210223_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='effector_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='effector_sequence',
            field=models.TextField(max_length=10000),
        ),
    ]
