# Generated by Django 3.1.6 on 2021-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20210223_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='effector_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='effector_sequence',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
