# Generated by Django 3.1.6 on 2021-02-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20210223_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
