# Generated by Django 3.1.6 on 2021-03-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20210223_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_id',
            field=models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
