# Generated by Django 3.1.6 on 2021-03-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20210302_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='effector_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
