# Generated by Django 3.1.6 on 2021-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('effector_id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('effector_sequence', models.TextField(max_length=10000, null=True)),
                ('effector_name', models.CharField(blank=True, default='', max_length=150)),
                ('effector_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('effector_signal_peptide', models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False'), ('', '')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('isolate', models.CharField(max_length=200)),
                ('interaction_partner', models.CharField(max_length=200)),
            ],
        ),
    ]
